name: Envcast Release

on:
    push:
        branches:
            - main
            - "v*" # Matches version tags like v1.0.0
    workflow_dispatch:

jobs:
    dry-run-and-release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Verify envcast --version
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  # Ensure GITHUB_TOKEN is set for the dry run step
                  if [ -z "$GITHUB_TOKEN" ]; then
                      echo "GITHUB_TOKEN is not set. Please set it in the repository secrets."
                      exit 1
                  fi

                  # Perform a dry run to verify the version
                  chmod +x ./main.sh &&
                  ./main.sh --version
            - name: Create Release
              if: success()
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: ${{ github.ref_name }}
                  name: Envcast ${{ github.ref_name }}
                  body: |
                      Automated release for envcast version ${{ github.ref_name }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
